language: php
sudo: required
dist: trusty
php:
- '7.2'
- '7.3'
before_script:
- sudo rm -f /etc/localtime
- sudo ln -s /usr/share/zoneinfo/UTC /etc/localtime
install:
- travis_retry composer install --no-interaction
- composer info -i
script:
- export PATH="$PATH:$PWD/vendor/bin"
- drutiny policy:list
